### ISSUE TITLE
how do i use it

### ISSUE THREAD

**Issue by mixserrm999** [mrepol742/Facebook-ChatBot-using-OpenAI#1]
not work for me

**Comment by mrepol742** [comment]
Hello @mixserrm999 

Clone this repository to your working directory via
```
git clone https://github.com/mrepol742/Facebook-ChatBot-using-OpenAI/
```
then open it
```
cd Facebook-ChatBot-using-OpenAI
```
First install the necessary packages
``` 
npm install
```

Open your browser and get your Facebook Cookie State, you can do this by installing this extension to your web browser
https://github.com/prj-orion/facebook-cookies

After that copy the facebook cookie array and save it to `appstate.json`

then run using 
```
npm run release
```

*WARNING* youre account may will be locked.

If you wanna you my AI send send a message to this account https://facebook.com/melvinjonesrepol It is active 24/7.

**Comment by mixserrm999** [comment]
Oh thanks it works
