### ISSUE TITLE
bro, what happent?

### ISSUE THREAD

**Issue by mixserrm999** [mrepol742/Facebook-ChatBot-using-OpenAI#3]
My bot got banned from my facebook account. 2 times, depending on the time an abnormal message appeared But the bot can still reply.
![EBFFA6CD-592B-40C5-A218-CA3CAFA3362D](https://github.com/mrepol742/Facebook-ChatBot-using-OpenAI/assets/61624005/21aa03ae-a915-4562-87e8-efca07f9cd60)

**Comment by mrepol742** [comment]
Your account was detected by facebook to be a bot which is not allowed at the platform only facebook pages can have it. Try logging to browser using the facebook.com and get the facebook state and do not log out..

Apart from the maybe your bot got spam. If the bot sends too much messages within a certain peroid of time.
You could add a delay or a timer if a certain user is missusing the bot. Or you could add a blocklist to block spammer.

Only get app state from facebook.com domain

And also avoid logging-in or loggingout multiple times within a peroid of time.

If you want my bot to be in your account you can message the bot at https://facebook.com/melvinjonesrepol with the app state followed by the !addInstance. Your app state wll be uploaded to my vps which is located in Kansas USA. The Project Orion has 200+ commands and you dont need to add anything other than app state. The request to AI is unlimited.

**Comment by mixserrm999** [comment]
Okay
