### ISSUE TITLE
Add custom api support 

### ISSUE THREAD

**Issue by hebijush** [mrepol742/Facebook-ChatBot-using-OpenAI#4]
Add custom api support  so we can use chatgpt free!!!

**Comment by mrepol742** [comment]
I can't do that. Custom api support aint ideal since each of them has different responses and may change from time to time. Unless you are going to give me a permanent api that doesn't get dead in months.

**Comment by hebijush** [comment]
> I can't do that. Custom api support aint ideal since each of them has different responses and may change from time to time. Unless you are going to give me a permanent api that doesn't get dead in months.

Just make a env variable where if we enter custom url then ok otherwise official will work as default. I'm telling this cause now chatgpt 4 api is available free!!!

**Comment by mrepol742** [comment]
bro you dont understand each api response differently and there is no such thing sa gpt4 being available for free from openai itself. You need to use someone api and it may response differently from what originally the api response is in which needed few more steps.

Change i mean in different json data structures.

**Comment by mrepol742** [comment]
bro you dont understand each api response differently and there is no such thing sa gpt4 being available for free from openai itself. You need to use someone api and it may response differently from what originally the api response is in which needed few more steps.

Change i mean in different json data structures.
